language: node_js
node_js: node
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  provider: heroku
  api_key:
    secure: fHPgS4/onYpwKYl8xDbelXX7EBozxr5vRe8dcwfXf0RwKSY1mUzi9RvYzDnJzr3mNg9AjGXf3sQHtfDI+9TNCD1hYusP3ZjeY+JZaKnork8Y4/Tle7wQNAZz6ARdfGlzEHKiHAotxAVsjxUGRhyseQfFJDI3Cb4zcNZvBcmuox7sDZiXAoLIFOOp44ZnVxSvL+WzbfDfW9MisKXvQnDDhs2e8SYQhik8hpXBqAxxTlMlQwv4gpmLjM+IoaSGftMi5WH4Y7KvgQ0hcvmfDREhW1MoXi71dThc+lrDmJoGE/CTfFfkWtNuInkYNhwhUoLj7WNErTDkisAdSE2xBVDD34DU3C51AGlYd97Rky4Ip7Y3B0+iM86I3kj9xHXtZeKylj4/BjHU1EAk3omKiD7XTbfRttV4KjBHheSXDxnOxjA4c1MRQ9pLIXmDAqP94hO/J3JGZ75+LYjh17gqAPz8XQzf3YK9bG3GtiaWyKxh+7DIvxAiFw8RRlAuB1Y+91Gmmm1umt43XQgAmvWD/UVUOY00T6GcfjumeSvjHxruLyS0e7UhLEOKj3OOSjK8KsGGYKmJMS96nv3fn1vCzF/CJ7bEunSerSmOvhPTiRqo4tIwXUI1UzDFTIGcwnAqqLfwR7BaqhGbQ/1EgXCw9KExyzxdnWUJYM0KXqtAJfbWeKA=
  app: beachtides
  on:
    repo: JacobMacInnis/beach-tides-client
